In [1]:
import kagglehub
path = kagglehub.dataset_download("jessicali9530/animal-crossing-new-horizons-nookplaza-dataset")

c:\ML\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\ypari\.cache\kagglehub\datasets\jessicali9530\animal-crossing-new-horizons-nookplaza-dataset\3.archive...

100%|██████████| 577k/577k [00:01<00:00, 510kB/s]

Extracting files...

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [8]:
import kagglehub
import os

path = kagglehub.dataset_download(
    "jessicali9530/animal-crossing-new-horizons-nookplaza-dataset"
)

print(path)
print(os.listdir(path))

C:\Users\ypari\.cache\kagglehub\datasets\jessicali9530\animal-crossing-new-horizons-nookplaza-dataset\versions\3
['accessories.csv', 'achievements.csv', 'art.csv', 'bags.csv', 'bottoms.csv', 'construction.csv', 'dress-up.csv', 'fencing.csv', 'fish.csv', 'floors.csv', 'fossils.csv', 'headwear.csv', 'housewares.csv', 'insects.csv', 'miscellaneous.csv', 'music.csv', 'other.csv', 'photos.csv', 'posters.csv', 'reactions.csv', 'recipes.csv', 'rugs.csv', 'shoes.csv', 'socks.csv', 'tools.csv', 'tops.csv', 'umbrellas.csv', 'villagers.csv', 'wall-mounted.csv', 'wallpaper.csv']

In [10]:
print(os.listdir(path))

['accessories.csv', 'achievements.csv', 'art.csv', 'bags.csv', 'bottoms.csv', 'construction.csv', 'dress-up.csv', 'fencing.csv', 'fish.csv', 'floors.csv', 'fossils.csv', 'headwear.csv', 'housewares.csv', 'insects.csv', 'miscellaneous.csv', 'music.csv', 'other.csv', 'photos.csv', 'posters.csv', 'reactions.csv', 'recipes.csv', 'rugs.csv', 'shoes.csv', 'socks.csv', 'tools.csv', 'tops.csv', 'umbrellas.csv', 'villagers.csv', 'wall-mounted.csv', 'wallpaper.csv']

In [39]:
dp = pd.read_csv(os.path.join(path, "tops.csv"))

dp.head()

,Name,Variation,DIY,Buy,Sell,Color 1,Color 2,Size,Miles Price,Source,...,Seasonal Availability,Mannequin Piece,Version,Style,Label Themes,Villager Equippable,Catalog,Filename,Internal ID,Unique Entry ID
0,A tee,NaN,No,560,140,Blue,White,1x1,NaN,Nook Shopping Catalog,...,All Year,No,1.0.0,Simple,everyday; comfy,Yes,For sale,TopsTexTopTshirtsHAce0,8532,7XCg953t2tGAPuzaR
1,acid-washed jacket,Blue,No,1680,420,Blue,Blue,1x1,NaN,Able Sisters,...,All Year,Yes,1.0.0,Simple,everyday; outdoorsy,Yes,For sale,TopsTexTopOuterLChemical0,5289,zAiLmCwSaWADqXkRf
2,acid-washed jacket,Black,No,1680,420,Black,Black,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Simple,everyday; outdoorsy,Yes,For sale,TopsTexTopOuterLChemical1,9538,K96PFk2AuQFqPrKH3
3,after-school jacket,Black,No,1050,262,Black,Red,1x1,NaN,Able Sisters,...,All Year,Yes,1.0.0,Cool,everyday; comfy,Yes,For sale,TopsTexTopYshirtsLGakuranopen0,4366,rAfEdHYdt5e4AGTya
4,after-school jacket,Berry red,No,1050,262,Red,Green,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Cool,everyday; comfy,Yes,For sale,TopsTexTopYshirtsLGakuranopen1,7554,mGvZuvYbGma2REd6A

<class 'pandas.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   1121 non-null   str
 1   Variation              1059 non-null   str
 2   DIY                    1121 non-null   str
 3   Buy                    1121 non-null   str
 4   Sell                   1121 non-null   int64
 5   Color 1                1121 non-null   str
 6   Color 2                1121 non-null   str
 7   Size                   1121 non-null   str
 8   Miles Price            5 non-null      float64
 9   Source                 1121 non-null   str
 10  Source Notes           1043 non-null   str
 11  Seasonal Availability  1121 non-null   str
 12  Mannequin Piece        1121 non-null   str
 13  Version                1121 non-null   str
 14  Style                  1121 non-null   str
 15  Label Themes           1121 non-null   str
 16  Villager Equippable    1121 non-null   str
 17  Catalog                1121 non-null   str
 18  Filename               1121 non-null   str
 19  Internal ID            1121 non-null   int64
 20  Unique Entry ID        1121 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 184.0 KB

              Sell  Miles Price   Internal ID
count  1121.000000     5.000000   1121.000000
mean    346.801070   640.000000   7835.410348
std     274.806254    89.442719   2331.777057
min      10.000000   600.000000   2401.000000
25%     240.000000   600.000000   7562.000000
50%     300.000000   600.000000   8270.000000
75%     375.000000   600.000000   9033.000000
max    4000.000000   800.000000  12983.000000

Name                        0
Variation                  62
DIY                         0
Buy                         0
Sell                        0
Color 1                     0
Color 2                     0
Size                        0
Miles Price              1116
Source                      0
Source Notes               78
Seasonal Availability       0
Mannequin Piece             0
Version                     0
Style                       0
Label Themes                0
Villager Equippable         0
Catalog                     0
Filename                    0
Internal ID                 0
Unique Entry ID             0
dtype: int64

Name                     0
Variation                0
DIY                      0
Buy                      0
Sell                     0
Color 1                  0
Color 2                  0
Size                     0
Miles Price              0
Source                   0
Source Notes             0
Seasonal Availability    0
Mannequin Piece          0
Version                  0
Style                    0
Label Themes             0
Villager Equippable      0
Catalog                  0
Filename                 0
Internal ID              0
Unique Entry ID          0
dtype: int64

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [41]:
dp.isnull().sum()

Name                        0
Variation                  62
DIY                         0
Buy                         0
Sell                        0
Color 1                     0
Color 2                     0
Size                        0
Miles Price              1116
Source                      0
Source Notes               78
Seasonal Availability       0
Mannequin Piece             0
Version                     0
Style                       0
Label Themes                0
Villager Equippable         0
Catalog                     0
Filename                    0
Internal ID                 0
Unique Entry ID             0
dtype: int64

In [45]:
dp.dropna(subset=['Variation','Source Notes'])

,Name,Variation,DIY,Buy,Sell,Color 1,Color 2,Size,Miles Price,Source,...,Seasonal Availability,Mannequin Piece,Version,Style,Label Themes,Villager Equippable,Catalog,Filename,Internal ID,Unique Entry ID
1,acid-washed jacket,Blue,No,1680,420,Blue,Blue,1x1,NaN,Able Sisters,...,All Year,Yes,1.0.0,Simple,everyday; outdoorsy,Yes,For sale,TopsTexTopOuterLChemical0,5289,zAiLmCwSaWADqXkRf
2,acid-washed jacket,Black,No,1680,420,Black,Black,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Simple,everyday; outdoorsy,Yes,For sale,TopsTexTopOuterLChemical1,9538,K96PFk2AuQFqPrKH3
3,after-school jacket,Black,No,1050,262,Black,Red,1x1,NaN,Able Sisters,...,All Year,Yes,1.0.0,Cool,everyday; comfy,Yes,For sale,TopsTexTopYshirtsLGakuranopen0,4366,rAfEdHYdt5e4AGTya
4,after-school jacket,Berry red,No,1050,262,Red,Green,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Cool,everyday; comfy,Yes,For sale,TopsTexTopYshirtsLGakuranopen1,7554,mGvZuvYbGma2REd6A
5,after-school jacket,Green,No,1050,262,Green,Yellow,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Cool,everyday; comfy,Yes,For sale,TopsTexTopYshirtsLGakuranopen2,7555,YHLqiyRYuF8BwEgaF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,young-royal shirt,White,No,1440,360,White,Green,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Gorgeous,fairy tale; formal; party; theatrical,Yes,For sale,TopsTexTopYshirtsLPrince0,4198,Y3nHGP5SBXZD8Jmeb
1116,young-royal shirt,Black,No,1440,360,Black,Red,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Gorgeous,fairy tale; formal; party; theatrical,Yes,For sale,TopsTexTopYshirtsLPrince1,8498,ntsoNan7oNNPebRgJ
1117,young-royal shirt,Pink,No,1440,360,Pink,Pink,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Gorgeous,fairy tale; formal; party; theatrical,Yes,For sale,TopsTexTopYshirtsLPrince2,8499,Q7rsY5EbzY2m6PAFE
1118,young-royal shirt,Blue,No,1440,360,Light blue,Blue,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Gorgeous,fairy tale; formal; party; theatrical,Yes,For sale,TopsTexTopYshirtsLPrince3,8500,fF5x8ZkHSRYfzBWiY
1119,young-royal shirt,Cream,No,1440,360,Yellow,Orange,1x1,NaN,Able Sisters,...,All Year,No,1.0.0,Gorgeous,fairy tale; formal; party; theatrical,Yes,For sale,TopsTexTopYshirtsLPrince4,8501,torBv4vydYwht5pvm

In [47]:
dp['Mannequin Piece'] =dp['Mannequin Piece'].astype(int)

ValueError: invalid literal for int() with base 10: 'No'