In [23]:
import warnings
import pandas as pd
import seaborn as sns

In [24]:
d = sns.load_dataset('titanic')

In [25]:
d.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
d.shape

(891, 15)

In [27]:

d.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [28]:
d.drop(['deck'],axis = 1,inplace=True)

In [30]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 79.4 KB

In [31]:
d.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
d['sex']=le.fit_transform(d['sex'])

In [36]:
d.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [37]:
d.drop(['who'],axis = 1,inplace = True)

In [38]:
d['alive']=le.fit_transform(d['alive'])

In [39]:
d.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,True,Southampton,0,False
1,1,1,0,38.0,1,0,71.2833,C,First,False,Cherbourg,1,False
2,1,3,0,26.0,0,0,7.9250,S,Third,False,Southampton,1,True
3,1,1,0,35.0,1,0,53.1000,S,First,False,Southampton,1,False
4,0,3,1,35.0,0,0,8.0500,S,Third,True,Southampton,0,True

In [40]:
d.drop([ "embark_town", "alive", "class","adult_male"], axis=1, inplace=True)

In [41]:
d.head()

   survived  pclass  sex   age  sibsp  parch     fare embarked  alone
0         0       3    1  22.0      1      0   7.2500        S  False
1         1       1    0  38.0      1      0  71.2833        C  False
2         1       3    0  26.0      0      0   7.9250        S   True
3         1       1    0  35.0      1      0  53.1000        S  False
4         0       3    1  35.0      0      0   8.0500        S   True